### ISSUE TITLE
ClassNotFoundException Bug

### ISSUE THREAD

**Issue by lizhangqu** [CtripMobile/DynamicAPK#12]
首次启动的时候进入app，点击进入插件，在插件页面异常结束app，再次进入app点击btn进入插件就会报找不到类

```
java.lang.ClassNotFoundException: ctrip.android.demo1.MainActivity
11-16 14:49:58.337 27070-27070/ctrip.android.sample W/System.err:     at java.lang.Class.classForName(Native Method)
11-16 14:49:58.337 27070-27070/ctrip.android.sample W/System.err:     at java.lang.Class.forName(Class.java:251)
11-16 14:49:58.337 27070-27070/ctrip.android.sample W/System.err:     at java.lang.Class.forName(Class.java:216)
11-16 14:49:58.338 27070-27070/ctrip.android.sample W/System.err:     at ctrip.android.sample.MainActivity$1.onClick(MainActivity.java:22)
11-16 14:49:58.338 27070-27070/ctrip.android.sample W/System.err:     at android.view.View.performClick(View.java:4444)
11-16 14:49:58.338 27070-27070/ctrip.android.sample W/System.err:     at android.view.View$PerformClick.run(View.java:18440)
11-16 14:49:58.339 27070-27070/ctrip.android.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
11-16 14:49:58.339 27070-27070/ctrip.android.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 14:49:58.339 27070-27070/ctrip.android.sample W/System.err:     at android.os.Looper.loop(Looper.java:136)
11-16 14:49:58.339 27070-27070/ctrip.android.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5016)
11-16 14:49:58.339 27070-27070/ctrip.android.sample W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-16 14:49:58.340 27070-27070/ctrip.android.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
11-16 14:49:58.340 27070-27070/ctrip.android.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
11-16 14:49:58.340 27070-27070/ctrip.android.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
11-16 14:49:58.340 27070-27070/ctrip.android.sample W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-16 14:49:58.341 27070-27070/ctrip.android.sample W/System.err: Caused by: java.lang.NoClassDefFoundError: ctrip/android/demo1/MainActivity
11-16 14:49:58.341 27070-27070/ctrip.android.sample W/System.err: 	... 15 more
11-16 14:49:58.342 27070-27070/ctrip.android.sample W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "ctrip.android.demo1.MainActivity" on path: DexPathList[[zip file "/data/app/ctrip.android.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/ctrip.android.sample-1, /vendor/lib, /system/lib]]
11-16 14:49:58.343 27070-27070/ctrip.android.sample W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-16 14:49:58.346 27070-27070/ctrip.android.sample W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
11-16 14:49:58.347 27070-27070/ctrip.android.sample W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
11-16 14:49:58.348 27070-27070/ctrip.android.sample W/System.err: 	... 15 more
```

**Comment by wangkang007** [comment]
我也遇到了这个bug 所以每次我都进行安装

**Comment by TediWang** [comment]
请看这个是否能帮助到你：https://github.com/CtripMobile/DynamicAPK/issues/3

**Comment by TediWang** [comment]
demo already fixed

**Comment by wangkang007** [comment]
谢谢
