### ISSUE TITLE
重新安装bundle的时候出错了

### ISSUE THREAD

**Issue by wangkang007** [CtripMobile/DynamicAPK#19]
11-20 12:40:46.626 29685-31468/com.sina.licaishi E/BundleCore: Error while dexopt >>>
                                                               java.io.IOException: unable to open DEX file
                                                                   at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                   at dalvik.system.DexFile.openDexFile(DexFile.java:296)
                                                                   at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                                   at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                                   at dalvik.system.DexPathList.loadDexFile(DexPathList.java:266)
                                                                   at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at ctrip.android.bundle.loader.BundlePathLoader$V19.makeDexElements(BundlePathLoader.java:222)
                                                                   at ctrip.android.bundle.loader.BundlePathLoader$V19.install(BundlePathLoader.java:197)
                                                                   at ctrip.android.bundle.loader.BundlePathLoader$V19.access$100(BundlePathLoader.java:183)
                                                                   at ctrip.android.bundle.loader.BundlePathLoader.installBundleDexs(BundlePathLoader.java:51)
                                                                   at ctrip.android.bundle.framework.storage.BundleArchiveRevision.optDexFile(BundleArchiveRevision.java:140)
                                                                   at ctrip.android.bundle.framework.storage.BundleAchive.optDexFile(BundleAchive.java:100)
                                                                   at ctrip.android.bundle.framework.BundleImpl.optDexFile(BundleImpl.java:119)
                                                                   at ctrip.android.bundle.framework.BundleCore.run(BundleCore.java:82)

**Comment by TediWang** [comment]
能否提供具体的操作过程。或者更新一下最新代码，之前有过一个fix。
