### ISSUE TITLE
按照使用方法build，还是会出现 java.lang.ClassNotFoundException:

### ISSUE THREAD

**Issue by zeuscoder** [CtripMobile/DynamicAPK#48]
01-14 10:10:43.979 2496-27871/? W/UpdateCheckService: get domain return null
01-14 10:10:44.559 27666-27666/? W/System.err: java.lang.ClassNotFoundException: ctrip.android.demo1.MainActivity
01-14 10:10:44.559 27666-27666/? W/System.err:     at java.lang.Class.classForName(Native Method)
01-14 10:10:44.559 27666-27666/? W/System.err:     at java.lang.Class.forName(Class.java:217)
01-14 10:10:44.559 27666-27666/? W/System.err:     at java.lang.Class.forName(Class.java:172)
01-14 10:10:44.559 27666-27666/? W/System.err:     at ctrip.android.sample.MainActivity$1.onClick(MainActivity.java:20)
01-14 10:10:44.559 27666-27666/? W/System.err:     at android.view.View.performClick(View.java:4084)
01-14 10:10:44.564 27666-27666/? W/System.err:     at android.view.View$PerformClick.run(View.java:17329)
01-14 10:10:44.564 27666-27666/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
01-14 10:10:44.564 27666-27666/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
01-14 10:10:44.564 27666-27666/? W/System.err:     at android.os.Looper.loop(Looper.java:137)
01-14 10:10:44.564 27666-27666/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4866)
01-14 10:10:44.569 27666-27666/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-14 10:10:44.569 27666-27666/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
01-14 10:10:44.569 27666-27666/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-14 10:10:44.569 27666-27666/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-14 10:10:44.569 27666-27666/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-14 10:10:44.569 27666-27666/? W/System.err: Caused by: java.lang.NoClassDefFoundError: ctrip/android/demo1/MainActivity
01-14 10:10:44.569 27666-27666/? W/System.err:  ... 15 more
01-14 10:10:44.574 27666-27666/? W/System.err: Caused by: java.lang.ClassNotFoundException: ctrip.android.demo1.MainActivity
01-14 10:10:44.574 27666-27666/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
01-14 10:10:44.574 27666-27666/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
01-14 10:10:44.574 27666-27666/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
01-14 10:10:44.574 27666-27666/? W/System.err:  ... 15 more

**Comment by cheukho** [comment]
你有改过源码吗？用gradle构建
