### ISSUE TITLE
Could not find com.android.tools.build:gradle:1.3.1.

### ISSUE THREAD

**Issue by loamen** [CtripMobile/DynamicAPK#51]
请问这是什么情况，我Android Studio用的就是'com.android.tools.build:gradle:1.3.1'没有问题。
![qq 20160125153451](https://cloud.githubusercontent.com/assets/8613083/12545013/8efc943e-c379-11e5-9107-b020024b9a0a.png)

it-010@it010:~/git/DynamicAPK$ gradle assembleRelease bundleRelease repackAll

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':classpath'.
  
  > Could not find com.android.tools.build:gradle:1.3.1.
  > Required by:
  >     :DynamicAPK:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by loamen** [comment]
![1](https://cloud.githubusercontent.com/assets/8613083/12692748/6fcb259c-c736-11e5-9bb7-8def91d09f32.png)
![2](https://cloud.githubusercontent.com/assets/8613083/12692747/6fbb743a-c736-11e5-833b-38101f1e46e5.png)

Android Studio里用携程代码里的镜像和开源中国的镜像都不行，用mavenCentral()可以。
而且无论用哪个执行“ gradle assembleRelease bundleRelease repackAll”都是“Could not find com.android.tools.build:gradle:1.3.1.”

**Comment by loamen** [comment]
`010:~/git/DynamicAPK$ gradle assembleRelease bundleRelease repackAll --stacktrace

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':classpath'.
  
  > Could not find com.android.tools.build:gradle:1.3.1.
  > Required by:
  >     :DynamicAPK:unspecified
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':classpath'.
      at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:52)
      at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:36)
      at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver$FilesAggregatingResolvedConfiguration.rethrowFailure(SelfResolvingDependencyResolver.java:104)
      at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver$ErrorHandlingResolvedConfiguration.rethrowFailure(ErrorHandlingArtifactDependencyResolver.java:72)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:461)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:202)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
      at org.gradle.api.internal.initialization.DefaultScriptHandler.updateClassPath(DefaultScriptHandler.java:36)
      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:118)
      at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
      at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:43)
      at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:466)
      at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
      at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
      at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
      at org.gradle.api.internal.Actions$CompositeAction.execute(Actions.java:78)
      at org.gradle.api.internal.Actions$TransformingActionAdapter.execute(Actions.java:130)
      at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:442)
      at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:437)
      at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:40)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
      at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:39)
      at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:25)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
      at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:48)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.Main.main(Main.java:39)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
  Caused by: org.gradle.api.internal.artifacts.ivyservice.ModuleVersionNotFoundException: Could not find com.android.tools.build:gradle:1.3.1.
  Required by:
  :DynamicAPK:unspecified
      at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.LazyDependencyToModuleResolver$StaticVersionResolveResult.notFound(LazyDependencyToModuleResolver.java:135)
      at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.LazyDependencyToModuleResolver$StaticVersionResolveResult.resolve(LazyDependencyToModuleResolver.java:96)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder$ModuleVersionSelectorResolveState.resolve(DependencyGraphBuilder.java:939)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder$DefaultModuleRevisionResolveState.getDescriptor(DependencyGraphBuilder.java:645)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:329)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:305)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:128)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:64)
      at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver.resolve(DefaultDependencyResolver.java:69)
      at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.create(CacheLockingArtifactDependencyResolver.java:36)
      at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.create(CacheLockingArtifactDependencyResolver.java:34)
      at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:124)
      at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:130)
      at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:53)
      at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:34)
      at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver.resolve(SelfResolvingDependencyResolver.java:39)
      at org.gradle.api.internal.artifacts.ivyservice.ShortcircuitEmptyConfigsArtifactDependencyResolver.resolve(ShortcircuitEmptyConfigsArtifactDependencyResolver.java:44)
      at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.resolve(ErrorHandlingArtifactDependencyResolver.java:37)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:240)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:230)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:459)
      ... 35 more

BUILD FAILED

Total time: 3.97 secs

it-010@it010:~/git/DynamicAPK$ 
`

**Comment by loamen** [comment]
`it-010@it010:~/git/DynamicAPK$ gradle assembleRelease bundleRelease repackAll --info
Starting Build
Settings evaluated using settings file '/home/it-010/git/DynamicAPK/settings.gradle'.
Projects loaded. Root project using build file '/home/it-010/git/DynamicAPK/build.gradle'.
Included projects: [root project 'DynamicAPK', project ':bundle', project ':demo1', project ':demo2', project ':sample']
Evaluating root project 'DynamicAPK' using build file '/home/it-010/git/DynamicAPK/build.gradle'.
Resource missing. [HTTP GET: http://repo1.maven.org/maven2/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.pom]
Resource missing. [HTTP HEAD: http://repo1.maven.org/maven2/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.jar]

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':classpath'.
  
  > Could not find com.android.tools.build:gradle:1.3.1.
  > Required by:
  >     :DynamicAPK:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2.953 secs
`
![qq 20160130103612](https://cloud.githubusercontent.com/assets/8613083/12693136/4f21b994-c73d-11e5-8bc8-773d82377ce6.png)
我用VPN，这两个文件都是可以访问的。

**Comment by BaoBaoJianqiang** [comment]
把maven注释了，还是使用jcenter即可，我这几天在看，试过了可以

**Comment by invinjun** [comment]
我的也提示了，修改为我平时用的版本就好了
